name: panel
channels:
  - conda-forge
  - defaults
dependencies:
  - _openmp_mutex=4.5=7_kmp_llvm
  - _python_abi3_support=1.0=hd8ed1ab_2
  - aiohappyeyeballs=2.6.1=pyhd8ed1ab_0
  - aiohttp=3.13.3=py312h9f8c436_0
  - aiosignal=1.4.0=pyhd8ed1ab_0
  - anyio=4.12.1=pyhcf101f3_0
  - appnope=0.1.4=pyhd8ed1ab_1
  - argon2-cffi=25.1.0=pyhd8ed1ab_0
  - argon2-cffi-bindings=25.1.0=py312h4409184_2
  - arrow=1.4.0=pyhcf101f3_0
  - asttokens=3.0.1=pyhd8ed1ab_0
  - async-lru=2.1.0=pyhcf101f3_0
  - attrs=25.4.0=pyhcf101f3_1
  - aws-c-auth=0.9.3=h1ddaa69_0
  - aws-c-cal=0.9.13=h6ee9776_1
  - aws-c-common=0.12.6=hc919400_0
  - aws-c-compression=0.3.1=h16f91aa_9
  - aws-c-event-stream=0.5.7=h9ae9c55_1
  - aws-c-http=0.10.7=h5928ca5_5
  - aws-c-io=0.23.3=hbe03c90_5
  - aws-c-mqtt=0.13.3=haf5c5c8_11
  - aws-c-s3=0.11.3=h8da9771_1
  - aws-c-sdkutils=0.2.4=h16f91aa_4
  - aws-checksums=0.2.7=h16f91aa_5
  - aws-crt-cpp=0.35.4=h74951b9_0
  - aws-sdk-cpp=1.11.606=h4e1b0f7_10
  - azure-core-cpp=1.16.2=he5ae378_0
  - azure-identity-cpp=1.13.3=h810541e_1
  - azure-storage-blobs-cpp=12.16.0=hc57151b_1
  - azure-storage-common-cpp=12.12.0=he467506_1
  - azure-storage-files-datalake-cpp=12.14.0=hf8a9d22_1
  - babel=2.18.0=pyhcf101f3_0
  - backports.zstd=1.3.0=py312h44dc372_0
  - beautifulsoup4=4.14.3=pyha770c72_0
  - bleach=6.3.0=pyhcf101f3_0
  - bleach-with-css=6.3.0=h5f6438b_0
  - blosc=1.21.6=h7dd00d9_1
  - bokeh=3.3.4=pyhd8ed1ab_0
  - brotli=1.2.0=h7d5ae5b_1
  - brotli-bin=1.2.0=hc919400_1
  - brotli-python=1.2.0=py312h0dfefe5_1
  - bzip2=1.0.8=hd037594_8
  - c-ares=1.34.6=hc919400_0
  - ca-certificates=2026.1.4=hbd8a1cb_0
  - cached-property=1.5.2=hd8ed1ab_1
  - cached_property=1.5.2=pyha770c72_1
  - cairo=1.18.4=he0f2337_1
  - cartopy=0.25.0=py312h5978115_1
  - certifi=2026.1.4=pyhd8ed1ab_0
  - cffi=2.0.0=py312h1b4d9a2_1
  - cftime=1.6.5=py312hf57c059_1
  - charset-normalizer=3.4.4=pyhd8ed1ab_0
  - cli11=2.6.0=h248ca61_0
  - click=8.3.1=pyh8f84b5b_1
  - cloudpickle=3.1.2=pyhcf101f3_1
  - colorcet=3.1.0=pyhd8ed1ab_1
  - comm=0.2.3=pyhe01879c_0
  - contourpy=1.3.3=py312h3093aea_4
  - cpython=3.12.12=py312hd8ed1ab_2
  - cycler=0.12.1=pyhcf101f3_2
  - cyrus-sasl=2.1.28=ha1cbb27_0
  - cytoolz=1.1.0=py312h4409184_1
  - dask=2026.1.2=pyhcf101f3_0
  - dask-core=2026.1.2=pyhcf101f3_0
  - datashader=0.18.2=pyhd8ed1ab_0
  - debugpy=1.8.20=py312h6510ced_0
  - decorator=5.2.1=pyhd8ed1ab_0
  - defusedxml=0.7.1=pyhd8ed1ab_0
  - distributed=2026.1.2=pyhcf101f3_0
  - double-conversion=3.4.0=haf25636_0
  - exceptiongroup=1.3.1=pyhd8ed1ab_0
  - executing=2.2.1=pyhd8ed1ab_0
  - fmt=12.1.0=h403dcb5_0
  - font-ttf-dejavu-sans-mono=2.37=hab24e00_0
  - font-ttf-inconsolata=3.000=h77eed37_0
  - font-ttf-source-code-pro=2.038=h77eed37_0
  - font-ttf-ubuntu=0.83=h77eed37_3
  - fontconfig=2.15.0=h1383a14_1
  - fonts-conda-ecosystem=1=0
  - fonts-conda-forge=1=hc364b38_1
  - fonttools=4.61.1=py312h5748b74_0
  - fqdn=1.5.1=pyhd8ed1ab_1
  - freetype=2.14.1=hce30654_0
  - frozenlist=1.7.0=py312h512c567_0
  - fsspec=2026.2.0=pyhd8ed1ab_0
  - geos=3.14.1=h5afe852_0
  - gflags=2.2.2=hf9b8971_1005
  - glew=2.2.0=hba38e01_0
  - glog=0.7.1=heb240a5_0
  - graphite2=1.3.14=hec049ff_2
  - h11=0.16.0=pyhcf101f3_1
  - h2=4.3.0=pyhcf101f3_0
  - harfbuzz=12.3.2=h3103d1b_0
  - hdf4=4.2.15=h2ee6834_7
  - hdf5=1.14.6=nompi_had3affe_106
  - holoviews=1.22.1=pyhd8ed1ab_0
  - hpack=4.1.0=pyhd8ed1ab_0
  - httpcore=1.0.9=pyh29332c3_0
  - httpx=0.28.1=pyhd8ed1ab_0
  - hyperframe=6.1.0=pyhd8ed1ab_0
  - icu=78.2=h38cb7af_0
  - idna=3.11=pyhd8ed1ab_0
  - importlib-metadata=8.7.0=pyhe01879c_1
  - importlib_resources=6.5.2=pyhd8ed1ab_0
  - ipykernel=7.2.0=pyh5552912_1
  - ipython=9.10.0=pyh53cf698_0
  - ipython_pygments_lexers=1.1.1=pyhd8ed1ab_0
  - ipywidgets=8.1.8=pyhd8ed1ab_0
  - isoduration=20.11.0=pyhd8ed1ab_1
  - jedi=0.19.2=pyhd8ed1ab_1
  - jinja2=3.1.6=pyhcf101f3_1
  - json5=0.13.0=pyhd8ed1ab_0
  - jsoncpp=1.9.6=h726d253_1
  - jsonpointer=3.0.0=pyhcf101f3_3
  - jsonschema=4.26.0=pyhcf101f3_0
  - jsonschema-specifications=2025.9.1=pyhcf101f3_0
  - jsonschema-with-format-nongpl=4.26.0=hcf101f3_0
  - jupyter=1.1.1=pyhd8ed1ab_1
  - jupyter-lsp=2.3.0=pyhcf101f3_0
  - jupyter_client=8.8.0=pyhcf101f3_0
  - jupyter_console=6.6.3=pyhd8ed1ab_1
  - jupyter_core=5.9.1=pyhc90fa1f_0
  - jupyter_events=0.12.0=pyh29332c3_0
  - jupyter_server=2.17.0=pyhcf101f3_0
  - jupyter_server_terminals=0.5.4=pyhcf101f3_0
  - jupyterlab=4.5.3=pyhd8ed1ab_0
  - jupyterlab_pygments=0.3.0=pyhd8ed1ab_2
  - jupyterlab_server=2.28.0=pyhcf101f3_0
  - jupyterlab_widgets=3.0.16=pyhcf101f3_1
  - kiwisolver=1.4.9=py312hd8c8125_2
  - krb5=1.21.3=h237132a_0
  - lark=1.3.1=pyhd8ed1ab_0
  - lcms2=2.18=hdfa7624_0
  - lerc=4.0.0=hd64df32_1
  - libabseil=20260107.0=cxx17_h2062a1b_0
  - libaec=1.1.5=h8664d51_0
  - libarrow=23.0.0=hb53654a_3_cpu
  - libarrow-acero=23.0.0=hbf36091_3_cpu
  - libarrow-compute=23.0.0=h4dbefc3_3_cpu
  - libarrow-dataset=23.0.0=hbf36091_3_cpu
  - libarrow-substrait=23.0.0=h05be00f_3_cpu
  - libblas=3.11.0=5_h51639a9_openblas
  - libbrotlicommon=1.2.0=hc919400_1
  - libbrotlidec=1.2.0=hc919400_1
  - libbrotlienc=1.2.0=hc919400_1
  - libcblas=3.11.0=5_hb0561ab_openblas
  - libclang-cpp19.1=19.1.7=default_hf3020a7_7
  - libclang13=21.1.8=default_h13b06bd_2
  - libcrc32c=1.1.2=hbdafb3b_0
  - libcurl=8.18.0=he38603e_0
  - libcxx=21.1.8=h55c6f16_2
  - libdeflate=1.25=hc11a715_0
  - libedit=3.1.20250104=pl5321hafb1f1b_0
  - libev=4.33=h93a5062_2
  - libevent=2.1.12=h2757513_1
  - libexpat=2.7.3=haf25636_0
  - libffi=3.5.2=hcf2aa1b_0
  - libfreetype=2.14.1=hce30654_0
  - libfreetype6=2.14.1=h6da58f4_0
  - libgcc=15.2.0=hcbb3090_17
  - libgfortran=15.2.0=h07b0088_17
  - libgfortran5=15.2.0=hdae7583_17
  - libglib=2.86.3=hfe11c1f_0
  - libgoogle-cloud=2.39.0=h2f60c08_1
  - libgoogle-cloud-storage=2.39.0=ha114238_1
  - libgrpc=1.78.0=h3e3f78d_1
  - libhwloc=2.12.2=default_ha3cc4f2_1000
  - libiconv=1.18=h23cfdf5_2
  - libintl=0.25.1=h493aca8_0
  - libjpeg-turbo=3.1.2=hc919400_0
  - liblapack=3.11.0=5_hd9741b5_openblas
  - libllvm19=19.1.7=h8e0c9ce_2
  - libllvm20=20.1.8=h8e0c9ce_1
  - libllvm21=21.1.8=h8e0c9ce_0
  - liblzma=5.8.2=h8088a28_0
  - libnetcdf=4.9.3=nompi_h80c4520_103
  - libnghttp2=1.67.0=hc438710_0
  - libntlm=1.8=h5505292_0
  - libogg=1.3.5=h48c0fde_1
  - libopenblas=0.3.30=openmp_ha158390_4
  - libopentelemetry-cpp=1.21.0=h08d5cc3_2
  - libopentelemetry-cpp-headers=1.21.0=hce30654_2
  - libparquet=23.0.0=h7a13205_3_cpu
  - libpng=1.6.54=h132b30e_0
  - libpq=18.1=h6caddbb_3
  - libprotobuf=6.33.5=h4a5acfd_0
  - libre2-11=2025.11.05=h4c27e2a_1
  - libsodium=1.0.20=h99b78c6_0
  - libsqlite=3.51.2=h1ae2325_0
  - libssh2=1.11.1=h1590b86_0
  - libtheora=1.1.1=h99b78c6_1006
  - libthrift=0.22.0=h14a376c_1
  - libtiff=4.7.1=h4030677_1
  - libutf8proc=2.11.3=h2431656_0
  - libvorbis=1.3.7=h81086ad_2
  - libwebp-base=1.6.0=h07db88b_0
  - libxcb=1.17.0=hdb1d25a_0
  - libxml2=2.15.1=h8d039ee_1
  - libxml2-16=2.15.1=h5ef1a60_1
  - libzip=1.11.2=h1336266_0
  - libzlib=1.3.1=h8359307_2
  - linkify-it-py=2.0.3=pyhd8ed1ab_1
  - llvm-openmp=21.1.8=h4a912ad_0
  - llvmlite=0.46.0=py312hc82e5dd_0
  - locket=1.0.0=pyhd8ed1ab_0
  - loguru=0.7.3=pyh707e725_0
  - lz4=4.4.5=py312h2b25a0d_1
  - lz4-c=1.10.0=h286801f_1
  - markdown=3.10.1=pyhcf101f3_0
  - markdown-it-py=4.0.0=pyhd8ed1ab_0
  - markupsafe=3.0.3=py312h5748b74_0
  - matplotlib-base=3.10.8=py312h605b88b_0
  - matplotlib-inline=0.2.1=pyhd8ed1ab_0
  - mdit-py-plugins=0.5.0=pyhd8ed1ab_0
  - mdurl=0.1.2=pyhd8ed1ab_1
  - mesalib=25.0.5=h7902562_2
  - mistune=3.2.0=pyhcf101f3_0
  - msgpack-python=1.1.2=py312h84eede6_1
  - multidict=6.7.0=py312hf0dca4a_0
  - multipledispatch=0.6.0=pyhd8ed1ab_1
  - munkres=1.1.4=pyhd8ed1ab_1
  - narwhals=2.16.0=pyhcf101f3_0
  - nbclient=0.10.4=pyhd8ed1ab_0
  - nbconvert-core=7.17.0=pyhcf101f3_0
  - nbformat=5.10.4=pyhd8ed1ab_1
  - ncurses=6.5=h5e97a16_3
  - nest-asyncio=1.6.0=pyhd8ed1ab_1
  - netcdf4=1.7.4=nompi_py312h5d59a02_102
  - nlohmann_json=3.12.0=h784d473_1
  - notebook=7.5.3=pyhcf101f3_0
  - notebook-shim=0.2.4=pyhd8ed1ab_1
  - numba=0.63.1=py312h5d8d915_0
  - numpy=1.26.4=py312h8442bc7_0
  - openjpeg=2.5.4=hbfb3c88_0
  - openldap=2.6.10=hbe55e7a_0
  - openssl=3.6.1=hd24854e_1
  - orc=2.2.2=h578b684_1
  - overrides=7.7.0=pyhd8ed1ab_1
  - packaging=26.0=pyhcf101f3_0
  - pandas=3.0.0=py312hae6be28_0
  - pandocfilters=1.5.0=pyhd8ed1ab_0
  - panel=1.3.1=pyhd8ed1ab_0
  - param=2.3.2=pyhc455866_0
  - parso=0.8.5=pyhcf101f3_0
  - partd=1.4.2=pyhd8ed1ab_0
  - pcre2=10.47=h30297fc_0
  - pexpect=4.9.0=pyhd8ed1ab_1
  - pillow=12.1.0=py312h4e908a4_0
  - pip=26.0.1=pyh8b19718_0
  - pixman=0.46.4=h81086ad_1
  - platformdirs=4.5.1=pyhcf101f3_0
  - pooch=1.9.0=pyhd8ed1ab_0
  - proj=9.7.1=hfb14a63_2
  - prometheus-cpp=1.3.0=h0967b3e_0
  - prometheus_client=0.24.1=pyhd8ed1ab_0
  - prompt-toolkit=3.0.52=pyha770c72_0
  - prompt_toolkit=3.0.52=hd8ed1ab_0
  - propcache=0.3.1=py312h998013c_0
  - psutil=7.2.2=py312hb3ab3e3_0
  - pthread-stubs=0.4=hd74edd7_1002
  - ptyprocess=0.7.0=pyhd8ed1ab_1
  - pugixml=1.15=hd3d436d_0
  - pure_eval=0.2.3=pyhd8ed1ab_1
  - pyarrow=23.0.0=py312h1f38498_0
  - pyarrow-core=23.0.0=py312h538510a_0_cpu
  - pycparser=2.22=pyh29332c3_1
  - pyct=0.6.0=pyhd8ed1ab_0
  - pygments=2.19.2=pyhd8ed1ab_0
  - pyobjc-core=12.1=py312h19bbe71_0
  - pyobjc-framework-cocoa=12.1=py312h1de3e18_0
  - pyparsing=3.3.2=pyhcf101f3_0
  - pyproj=3.7.2=py312h66ed876_2
  - pyshp=3.0.3=pyhd8ed1ab_0
  - pysocks=1.7.1=pyha55dd90_7
  - python=3.12.12=h18782d2_2_cpython
  - python-dateutil=2.9.0.post0=pyhe01879c_2
  - python-fastjsonschema=2.21.2=pyhe01879c_0
  - python-gil=3.12.12=hd8ed1ab_2
  - python-json-logger=2.0.7=pyhd8ed1ab_0
  - python-tzdata=2025.3=pyhd8ed1ab_0
  - python_abi=3.12=8_cp312
  - pytz=2025.2=pyhd8ed1ab_0
  - pyvista=0.46.5=pyhd8ed1ab_0
  - pyviz_comms=3.0.6=pyhd8ed1ab_0
  - pyyaml=6.0.3=py312h04c11ed_1
  - pyzmq=27.1.0=py312hd65ceae_0
  - qhull=2020.2=h420ef59_5
  - qt6-main=6.10.2=h9aec236_4
  - re2=2025.11.05=ha480c28_1
  - readline=8.3=h46df422_0
  - referencing=0.37.0=pyhcf101f3_0
  - requests=2.32.5=pyhcf101f3_1
  - rfc3339-validator=0.1.4=pyhd8ed1ab_1
  - rfc3986-validator=0.1.1=pyh9f0ad1d_0
  - rfc3987-syntax=1.1.0=pyhe01879c_1
  - rpds-py=0.30.0=py312h6ef9ec0_0
  - scipy=1.17.0=py312h0f234b1_1
  - scooby=0.11.0=pyhd8ed1ab_0
  - send2trash=2.1.0=pyh5552912_0
  - setuptools=82.0.0=pyh332efcf_0
  - shapely=2.1.2=py312h35cd81b_2
  - six=1.17.0=pyhe01879c_1
  - snappy=1.2.2=hada39a4_1
  - sniffio=1.3.1=pyhd8ed1ab_2
  - sortedcontainers=2.4.0=pyhd8ed1ab_1
  - soupsieve=2.8.3=pyhd8ed1ab_0
  - spirv-tools=2025.5=h4ddebb9_0
  - sqlite=3.51.2=h77b7338_0
  - stack_data=0.6.3=pyhd8ed1ab_1
  - tbb=2022.3.0=h4ddebb9_2
  - tblib=3.2.2=pyhcf101f3_0
  - terminado=0.18.1=pyhc90fa1f_1
  - tinycss2=1.5.1=pyhcf101f3_0
  - tk=8.6.13=h010d191_3
  - tomli=2.4.0=pyhcf101f3_0
  - toolz=1.1.0=pyhd8ed1ab_1
  - tornado=6.5.4=py312h4409184_0
  - tqdm=4.67.3=pyh8f84b5b_0
  - traitlets=5.14.3=pyhd8ed1ab_1
  - typing-extensions=4.15.0=h396c80c_0
  - typing_extensions=4.15.0=pyhcf101f3_0
  - typing_utils=0.1.0=pyhd8ed1ab_1
  - tzdata=2025c=hc9c84f9_1
  - uc-micro-py=1.0.3=pyhd8ed1ab_1
  - unicodedata2=17.0.0=py312h4409184_1
  - uri-template=1.3.0=pyhd8ed1ab_1
  - urllib3=2.6.3=pyhd8ed1ab_0
  - utfcpp=4.09=hce30654_0
  - viskores=1.1.0=h052cd35_0
  - vtk-base=9.5.2=py312h50b3ee4_7
  - wcwidth=0.6.0=pyhd8ed1ab_0
  - webcolors=25.10.0=pyhd8ed1ab_0
  - webencodings=0.5.1=pyhd8ed1ab_3
  - websocket-client=1.9.0=pyhd8ed1ab_0
  - wheel=0.46.3=pyhd8ed1ab_0
  - widgetsnbextension=4.0.15=pyhd8ed1ab_0
  - wslink=2.5.0=pyhd8ed1ab_0
  - xarray=2026.1.0=pyhcf101f3_0
  - xorg-libx11=1.8.12=h6a5fb8c_0
  - xorg-libxau=1.0.12=hc919400_1
  - xorg-libxdmcp=1.1.5=hc919400_1
  - xorg-libxext=1.3.7=h84a0fba_0
  - xorg-libxrandr=1.5.5=h84a0fba_0
  - xorg-libxrender=0.9.12=h5505292_0
  - xorg-libxshmfence=1.3.3=h5505292_0
  - xyzservices=2025.11.0=pyhd8ed1ab_0
  - yaml=0.2.5=h925e9cb_3
  - yarl=1.22.0=py312h5748b74_0
  - zeromq=4.3.5=h888dc83_9
  - zfp=1.0.1=ha86207d_5
  - zict=3.0.0=pyhd8ed1ab_1
  - zipp=3.23.0=pyhcf101f3_1
  - zlib=1.3.1=h8359307_2
  - zlib-ng=2.3.3=hed4e4f5_1
  - zstd=1.5.7=hbf9d68e_6
prefix: /Users/vapor/miniconda3/envs/panel
